version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.0-node
    steps:
      - checkout
      - run:
          name: Install PHP dependencies
          command: composer install
      - php/install-packages
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit
  echo-hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Echo Hello World
          command: echo "Hello World"
workflows:
  build-and-test:
    jobs:
      - test-php
      - echo-hello-world
